- name: Configuration initiale du serveur
  hosts: worskpace
  become: true
  vars:
    new_user: r  # Nom du nouvel utilisateur
    ssh_public_key_path: "~/.ssh/id_rsa.pub"  # Chemin vers votre clé publique locale
  tasks:
    # 1. Mettre à jour le système
    - name: Mettre à jour les packages
      apt:
        update_cache: yes
        upgrade: dist

    # 2. Installer des outils essentiels
    - name: Installer des outils de base
      apt:
        name:
          - vim
          - git
          - curl
          - ufw
        state: present

    # 3. Configurer le pare-feu UFW pour autoriser SSH
    - name: Activer le pare-feu et autoriser SSH
      ufw:
        rule: allow
        name: OpenSSH
        state: enabled

    # 4. Créer un nouvel utilisateur
    - name: Créer un utilisateur "{{ new_user }}"
      user:
        name: "{{ new_user }}"
        groups: sudo
        shell: /bin/bash
        create_home: true
        state: present

    # 5. Configurer la clé SSH pour le nouvel utilisateur
    - name: Créer le répertoire .ssh pour "{{ new_user }}"
      file:
        path: "/home/{{ new_user }}/.ssh"
        state: directory
        owner: "{{ new_user }}"
        group: "{{ new_user }}"
        mode: '0700'

    - name: Ajouter une clé publique SSH pour "{{ new_user }}"
      copy:
        dest: "/home/{{ new_user }}/.ssh/authorized_keys"
        content: "{{ lookup('file', ssh_public_key_path) }}"
        owner: "{{ new_user }}"
        group: "{{ new_user }}"
        mode: '0600'

    # 6. S'assurer que le mot de passe sudo n'est pas requis pour le nouvel utilisateur
    - name: Ajouter "{{ new_user }}" au fichier sudoers sans mot de passe
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: "^{{ new_user }}.*"
        line: "{{ new_user }} ALL=(ALL) NOPASSWD:ALL"
