- name: Vérification de la configuration Ansible
  hosts: cluster
  become: false  # Pas besoin d'utiliser sudo pour un simple test
  tasks:
    - name: Vérifier la connectivité avec le module ping
      ping: