- name: Configuration initiale du serveur
  hosts: worskpace
  become: true
  tasks:
    # 1. Mettre à jour le système
    - name: Mettre à jour les packages
      dnf:
        name: "*"
        state: latest

    # 2. Installer des outils essentiels
    - name: Installer des outils de base
      dnf:
        name:
          - vim
          - git
          - curl
          - micro
        state: present