- name: Configuration ssh du serveur
  hosts: worskpace
  become: true
  vars:
    ssh_port: 22  # Port SSH (remplacez si nécessaire)
  tasks:
    - name: Sauvegarder la configuration actuelle de SSH
      copy:
        src: /etc/ssh/sshd_config
        dest: /etc/ssh/sshd_config.bak
        remote_src: true

    - name: Configurer le port SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?Port"
        line: "Port {{ ssh_port }}"
        state: present

    - name: Désactiver le login root
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?PermitRootLogin"
        line: "PermitRootLogin no"
        state: present

    - name: Désactiver l'authentification par mot de passe
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?PasswordAuthentication"
        line: "PasswordAuthentication no"
        state: present

    - name: Redémarrer le service SSH
      service:
        name: sshd
        state: restarted
