- name: Créer une clé SSH pour un utilisateur
  hosts: workspace
  become: true
  vars:
    user: jbwittner  # Nom du nouvel utilisateur
    ssh_key_path: "/home/{{ user }}/.ssh/github_id_ed25519"
  tasks:
    - name: Vérifier si la clé SSH existe déjà
      ansible.builtin.stat:
        path: "{{ ssh_key_path }}"
      register: ssh_key_check

    - name: Générer une paire de clés SSH pour "{{ user }}" et GitHub si elle n'existe pas
      ansible.builtin.user:
        name: "{{ user }}"
        generate_ssh_key: yes
        ssh_key_type: ed25519
        ssh_key_file: ".ssh/github_id_ed25519"
        force: no
      when: not ssh_key_check.stat.exists

    - name: Configurer le fichier SSH config pour GitHub
      ansible.builtin.blockinfile:
        path: "/home/{{ user }}/.ssh/config"
        create: yes
        block: |
          Host github.com
            HostName github.com
            User git
            IdentityFile {{ ssh_key_path }}
            IdentitiesOnly yes
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0600"

    - name: Assurer les permissions correctes pour le dossier .ssh
      ansible.builtin.file:
        path: "/home/{{ user }}/.ssh"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0700"

    - name: Assurer les permissions correctes pour la clé privée
      ansible.builtin.file:
        path: "{{ ssh_key_path }}"
        state: file
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0600"

    - name: Assurer les permissions correctes pour le fichier SSH config
      ansible.builtin.file:
        path: "/home/{{ user }}/.ssh/config"
        state: file
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0600"
