- name: Installer Zsh et Oh My Zsh
  hosts: workspace
  become: true
  vars:
    user: jbwittner
    zsh_path: "/bin/zsh"
    oh_my_zsh_install_script: "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh"
    oh_my_zsh_dir: "/home/{{ user }}/.oh-my-zsh"

  tasks:
    - name: Installer Zsh
      ansible.builtin.package:
        name: zsh
        state: present

    - name: Définir Zsh comme shell par défaut pour l'utilisateur
      ansible.builtin.user:
        name: "{{ user }}"
        shell: "{{ zsh_path }}"

    - name: Installer Git (nécessaire pour Oh My Zsh)
      ansible.builtin.package:
        name: git
        state: present

    - name: Vérifier si Oh My Zsh est déjà installé
      ansible.builtin.stat:
        path: "{{ oh_my_zsh_dir }}"
      register: oh_my_zsh_status

    - name: Installer Oh My Zsh de manière non interactive
      ansible.builtin.command:
        cmd: >
          sh -c "$(curl -fsSL {{ oh_my_zsh_install_script }})" "" --unattended
      become_user: "{{ user }}"
      environment:
        HOME: "/home/{{ user }}"
      when: not oh_my_zsh_status.stat.exists

    - name: Assurer que le propriétaire du répertoire Oh My Zsh est correct
      ansible.builtin.file:
        path: "{{ oh_my_zsh_dir }}"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        recurse: true

    - name: Assurer que le fichier .zshrc appartient à l'utilisateur
      ansible.builtin.file:
        path: "/home/{{ user }}/.zshrc"
        state: file
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0644"
        force: no

    - name: Install zsh-autosuggestions plugin # noqa: latest
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-autosuggestions
        dest: /home/{{ user }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions
        depth: 1
      become_user: "{{ user }}"

    - name: Install zsh-completions plugin # noqa: latest
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-completions
        dest: /home/{{ user }}/.oh-my-zsh/custom/plugins/zsh-completions
        depth: 1
      become_user: "{{ user }}"

    - name: Install zsh-syntax-highlighting plugin # noqa: latest
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: /home/{{ user }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
        depth: 1
      become_user: "{{ user }}"
