- name: Installer Lazydocker
  hosts: workspace
  become: true
  vars:
    version: 0.24.1

  tasks:
    - name: Télécharger Lazydocker
      get_url:
        url: "https://github.com/jesseduffield/lazydocker/releases/download/v0.24.1/lazydocker_{{ version }}_Linux_x86_64.tar.gz"
        dest: "/tmp/lazydocker_Linux_x86_64.tar.gz"
    
    - name: Extraire l'archive Lazydocker
      ansible.builtin.unarchive:
        src: "/tmp/lazydocker_Linux_x86_64.tar.gz"
        dest: "/usr/local/bin"
        remote_src: true
        creates: "/usr/local/bin/lazydocker"