- name: Installer Lazygit
  hosts: workspace
  become: true
  vars:
    version: 0.44.1

  tasks:
    - name: Télécharger Lazygit
      get_url:
        url: "https://github.com/jesseduffield/lazygit/releases/download/v{{ version }}/lazygit_{{ version }}_Linux_x86_64.tar.gz"
        dest: "/tmp/lazygit_Linux_x86_64.tar.gz"
    
    - name: Extraire l'archive Lazygit
      ansible.builtin.unarchive:
        src: "/tmp/lazygit_Linux_x86_64.tar.gz"
        dest: "/usr/local/bin"
        remote_src: true
        creates: "/usr/local/bin/lazygit"