- name: Installer Volta sur une machine distante
  hosts: workspace
  become: true
  vars:
    user: jbwittner  # Nom de l'utilisateur cible
  tasks:
    - name: Installer curl si non présent
      dnf:
        name: curl
        state: present

    - name: Télécharger et installer Volta
      shell: curl https://get.volta.sh | bash
      become_user: "{{ user }}"

    - name: Installer Pnpm
      shell: volta install pnpm
      become_user: "{{ user }}"