- name: Installer SDKMAN! pour un utilisateur unique
  hosts: workspace
  become: true
  vars:
    user: jbwittner  # Nom de l'utilisateur cible
  tasks:
    # 1. Vérifier que le répertoire home de l'utilisateur existe
    - name: Vérifier que le répertoire home existe
      file:
        path: "/home/{{ user }}"
        state: directory

    # 2. Installer les dépendances nécessaires pour SDKMAN!
    - name: Installer curl et zip (dépendances SDKMAN)
      apt:
        name:
          - curl
          - zip
        state: present
      when: ansible_os_family == "Debian"

    # 3. Télécharger et installer SDKMAN!
    - name: Télécharger et installer SDKMAN!
      shell: |
        curl -s "https://get.sdkman.io" | bash
      args:
        executable: /bin/bash
        creates: "/home/{{ user }}/.sdkman"
      become_user: "{{ user }}"

    # 4. Ajouter SDKMAN! au fichier .bashrc
    - name: Ajouter SDKMAN! au fichier .bashrc
      lineinfile:
        path: "/home/{{ user }}/.bashrc"
        line: |
          export SDKMAN_DIR="/home/{{ user }}/.sdkman"
          [[ -s "$SDKMAN_DIR/bin/sdkman-init.sh" ]] && source "$SDKMAN_DIR/bin/sdkman-init.sh"
        state: present
      owner: "{{ user }}"
      group: "{{ user }}"

    # 5. (Optionnel) Installer un SDK via SDKMAN! (ex. Java)
    - name: Installer Java via SDKMAN!
      shell: |
        source /home/{{ user }}/.sdkman/bin/sdkman-init.sh && sdk install java
      args:
        executable: /bin/bash
      become_user: "{{ user }}"
